version: 0.2

env:
  variables:
    STACK_NAME: simple-s3-lambda
    CODE_KEY: "function-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm --version
      - pip install --quiet awscli
  pre_build:
    commands:
      - echo "⏳ Zipping Lambda code..."
      - zip -j $CODE_KEY src/index.js
      - aws s3 cp $CODE_KEY s3://$ARTIFACT_BUCKET/$CODE_KEY
  build:
    commands:
      - echo "⏳ Deploying CloudFormation stack..."
      - aws cloudformation deploy \
        --template-file template.yaml \
        --stack-name $STACK_NAME \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameter-overrides CodeS3Bucket=$ARTIFACT_BUCKET CodeS3Key=$CODE_KEY
  post_build:
    commands:
      - echo "✅ Deployment finished."

artifacts:
  files:
    - template.yaml
