AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 → Lambda prints TXT (pure CloudFormation, zero circular deps)

# ---------------------------------------------------------------------------#
# Parameters                                                                 #
# ---------------------------------------------------------------------------#
Parameters:
  CodeS3Bucket:
    Type: String
    Description: S3 bucket chứa file ZIP của Lambda
  CodeS3Key:
    Type: String
    Description: S3 key (đường dẫn) tới file ZIP Lambda

# ---------------------------------------------------------------------------#
# Resources                                                                  #
# ---------------------------------------------------------------------------#
Resources:

  # 1. IAM role cho Lambda (KHÔNG reference bucket)
  LambdaExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess   # đủ để đọc object

  # 2. Lambda function in Node.js 20
  PrintFileFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: print-file-content
      Runtime: nodejs20.x
      Handler: index.handler
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt LambdaExecRole.Arn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key:    !Ref CodeS3Key

  # 3. Quyền để S3 invoke Lambda (KHÔNG reference bucket)
  PermissionForS3Invoke:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PrintFileFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId   # tránh circular dep

  # 4. S3 bucket, cấu hình notification sau khi có permission
  InputBucket:
    Type: AWS::S3::Bucket
    DependsOn: PermissionForS3Invoke        # đảm bảo quyền đã sẵn sàng
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt PrintFileFunction.Arn

# ---------------------------------------------------------------------------#
# Outputs                                                                    #
# ---------------------------------------------------------------------------#
Outputs:
  BucketName:
    Description: Tên S3 bucket để upload file .txt
    Value: !Ref InputBucket

  LambdaName:
    Description: Tên Lambda function
    Value: !Ref PrintFileFunction

  LambdaArn:
    Description: ARN Lambda – tiện để monitor/log
    Value: !GetAtt PrintFileFunction.Arn